### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by sigfriedCub1990** [react-hook-form/react-hook-form-devtools#1]
Hi @bluebill1049 ,

I've been working with `react-hook-forms` for a while and the results are great. In return I would love to contribute to this repo in any way I can.

Cheers, sigfried.

**Comment by bluebill1049** [comment]
aha that would be awesome! I will keep you in the loop on what we can work together.  you can take a preview on V1 there is a branch now.

**Comment by bluebill1049** [comment]
It's going to be an interesting and useful project :)

**Comment by bluebill1049** [comment]
<img width="1440" alt="Screen Shot 2020-02-10 at 8 03 00 am 2" src="https://user-images.githubusercontent.com/10513364/74109896-c7c94980-4bdb-11ea-8660-515c8eca7858.png">

**Comment by bluebill1049** [comment]
<img width="1078" alt="Screen Shot 2020-02-10 at 8 03 48 am" src="https://user-images.githubusercontent.com/10513364/74109914-e7607200-4bdb-11ea-8a95-bffb4126dd8b.png">

**Comment by sigfriedCub1990** [comment]
> It's going to be an interesting and useful project :)

Indeed :+1:

**Comment by bluebill1049** [comment]
Hey @sigfriedCub1990 you want to help on the filter functionality?

<img width="290" alt="Screen Shot 2020-02-10 at 2 22 21 pm" src="https://user-images.githubusercontent.com/10513364/74118768-e3027c00-4c10-11ea-8f8a-428d8f11d008.png">

the filter name part?

```
cd app
yarn
yarn start
```

everything lives inside the `devTools` folder.

**Comment by sigfriedCub1990** [comment]
Sure thing @bluebill1049 I'll look into it today's afternoon :)

**Comment by bluebill1049** [comment]
@kotarella1110 if you got sometimes, please help improve the types :) ❤️

**Comment by kotarella1110** [comment]
@bluebill1049 yeah! i will improve types 💚

**Comment by bluebill1049** [comment]
amazing! @kotarella1110 🙏

**Comment by bluebill1049** [comment]
it's an ongoing thing, let's close this issue for now. feel free to send PR to improve this devtool
