### ISSUE TITLE
Report Errors

### ISSUE THREAD

**Issue by hungnguyen1995** [react-hook-form/react-hook-form-devtools#10]
I'm using on Next js  

ReferenceError: window is not defined
    at Object.<anonymous> (D:\source\fe-codebase\node_modules\react-hook-form-devtools\dist\react-hook-form-devtools.js:419:35)
____

littleStateMachine.setStorageType(window.localStorage);

**Comment by bluebill1049** [comment]
aha good one, i forgot about SSR. will patch soon.

**Comment by bluebill1049** [comment]
hey @hungnguyen1995 can you test out this beta version: `1.1.2-beta.1`

**Comment by hungnguyen1995** [comment]
> hey @hungnguyen1995 can you test out this beta version: `1.1.2-beta.1`

ok bro ! thanks u

**Comment by hungnguyen1995** [comment]
![image](https://user-images.githubusercontent.com/38306234/76539296-29b6f080-64b3-11ea-8fb7-c1579a45d8c3.png)
i was checkout 1.1.2-beta.1
