### ISSUE TITLE
Step to do in order for the RHFD form showing up

### ISSUE THREAD

**Issue by zenzjtech** [react-hook-form/react-hook-form-devtools#16]
I've installed the app, but haven't been able to figure out how to make the UI appear.
Note:

- I include it in the child components, not on the App.js
- My react, and other package are latest.

![image](https://user-images.githubusercontent.com/10528635/78122611-3639c380-7437-11ea-9981-7c8fbc6b49ce.png)

**Comment by bluebill1049** [comment]
strange... can you inspect the DOM? it should worked.

**Comment by zenzjtech** [comment]
Hi @bluebill1049, Thank you for your response.
My plan is to reproducing it in some sites like Codesandbox.
However, currently I don't have time to reproduce the issue. So let me close the issue and reopen it in the future.

**Comment by bluebill1049** [comment]
cool sounds good thanks
