### ISSUE TITLE
little-state-machine causes React native to crash

### ISSUE THREAD

**Issue by Albert-Gao** [react-hook-form/react-hook-form-devtools#17]
![image](https://user-images.githubusercontent.com/18282328/78837969-465e2e00-7a49-11ea-99c7-f3fd63540d1e.png)

It tries to access something not there
![image](https://user-images.githubusercontent.com/18282328/78838984-858d7e80-7a4b-11ea-842c-122ba3ed3136.png)

I do not if it is intended because of not supporting RN? Or something just we can fix?

Thanks, great tool BTW!

**Comment by bluebill1049** [comment]
oh, sorry @Albert-Gao it's not compatible with React Native. I will add a note to it.

**Comment by Albert-Gao** [comment]
Thanks! :)

**Comment by bluebill1049** [comment]
wow you are a quick replier! hahaha

**Comment by Albert-Gao** [comment]
like you ! 😂

**Comment by listepo** [comment]
@Albert-Gao what do you think about adding this as [fbflipper plugin](https://fbflipper.com/docs/extending/index)?

**Comment by bluebill1049** [comment]
hey @listepo i don't think it's working with RN at all at the moment. all elements are DOM elements. I am not too familiar with that plugin as well.

**Comment by superandrew** [comment]
is this reported somewhere? because I fell into the same trap and had to discover this to realize 😂
