### ISSUE TITLE
Don't include in Production build, like React Query Devtools

### ISSUE THREAD

**Issue by cliffordp** [react-hook-form/react-hook-form-devtools#18]
From https://github.com/tannerlinsley/react-query-devtools#usage
> By default, React Query Devtools are not imported and used when `process.env.NODE_ENV === 'production'`, so you don't need to worry about excluding them during a production build.

And the code looks easy, too! https://github.com/tannerlinsley/react-query-devtools/blob/v1.0.12/index.js

===

I really like this utility (thanks!) but don't want to have to remember to remove from my component to build an optimized bundle, as _RFH_ itself is the 1st (IE11) and 6th (core) heaviest things I've got (is there room for improvement for IE11?) and the 2nd heaviest is a dependency of _RFH DevTools_.

Details from an _unminified_ build:

<img width="878" alt="Screen Shot 2020-04-20 at 12 10 59 AM" src="https://user-images.githubusercontent.com/1812179/79716226-aa7bc000-829b-11ea-8103-9284ebebf1cb.png">

<img width="798" alt="Screen Shot 2020-04-20 at 12 13 05 AM" src="https://user-images.githubusercontent.com/1812179/79716266-d1d28d00-829b-11ea-87b6-948197f98e50.png">

**Comment by bluebill1049** [comment]
want to send a PR?

**Comment by cliffordp** [comment]
Yes, I'd want to ;) But I looked through and am unsure how/where to modify and wasn't sure how tests would fail. Unsure how to proceed.

**Comment by bluebill1049** [comment]
I think this file is all you need right? https://github.com/react-hook-form/react-hook-form-devtools/blob/master/src/index.tsx

**Comment by cliffordp** [comment]
Oh, nice, will try. tyvm

**Comment by cliffordp** [comment]
Well I've been at it for an hour and can't even get a local clone of your master branch to build... so I can't then test if any changes would be working :(

FYI: I've never used TypeScript or Rollup before, but I am using PhpStorm and globally installed rollup just now on Mac.

> \> react-hook-form-devtools@1.1.3 build .../react-hook-form-devtools
> \> rollup -c
> >
> src/index.tsx → dist/react-hook-form-devtools.js, dist/react-hook-form-devtools.es.js...
> (!) Unresolved dependencies
> https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
> little-state-machine (imported by src/devTool.tsx, src/devToolUI.tsx, src/panel.tsx)
> [!] (plugin rpt2) Error: .../react-hook-form-devtools/src/styled.tsx(9,7): semantic error TS2742: The inferred type of 'Button' cannot be named without a reference to 'react-hook-form-devtools/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
> src/styled.tsx
> Error: .../react-hook-form-devtools/src/styled.tsx(9,7): semantic error TS2742: The inferred type of 'Button' cannot be named without a reference to 'react-hook-form-devtools/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.

You and your code have been very helpful to me so I really wanted to help, but I guess it's not going to happen today. Sorry about that.

**Comment by bluebill1049** [comment]
nah @cliffordp don't be sorry at all, i will get it out today. 👍

**Comment by cliffordp** [comment]
🥇

**Comment by bluebill1049** [comment]
hmmm looks like it's difficult to do dynamic export in TS, may have to do that check at the app level. I will update the read me to include that production checks instead.

**Comment by cliffordp** [comment]
I see it's updated. tyvm.

Is there room for improvement in how the component is exported/built so we don't need this manual check everywhere we want to use it? If yes, is there anything I can try to help with?

**Comment by cliffordp** [comment]
Also my build doesn't change as a result, just that the DevTool doesn't show up on the page.

Could you move more (or everything) from "dependencies" to "devDependencies"?
https://github.com/tannerlinsley/react-query-devtools/blob/master/package.json has only 1 dependency.

**Comment by bluebill1049** [comment]
> Also my build doesn't change as a result, just that the DevTool doesn't show up on the page.
> 
> Could you move more (or everything) from "dependencies" to "devDependencies"?
> https://github.com/tannerlinsley/react-query-devtools/blob/master/package.json has only 1 dependency.

good point!

**Comment by bluebill1049** [comment]
if you can, send a PR on this 🙏

**Comment by cliffordp** [comment]
I tried for a while and yarn install works but running `build` does not, throwing this error (even if I add `// @ts-ignore` on the line above, as PhpStorm suggested):

> TS2742: The inferred type of 'Button' cannot be named without a reference to 'react-hook-form-devtools/node_modules/@emotion/styled-base'. This is likely not portable. A type annotation is necessary.

![image](https://user-images.githubusercontent.com/1812179/79932641-9e1a7300-8413-11ea-85d4-6aed3c3cfcbc.png)

So... I have no idea if it works, but I submitted the PR to move everything from dep to devDep. I ran `yarn install` but the lock file didn't update. I'm assuming it was supposed to.

**Comment by bluebill1049** [comment]
I will release a beta and we can test it out :)

**Comment by bluebill1049** [comment]
`react-hook-form-devtools@1.1.5-beta.1` can you try this beta?

**Comment by cliffordp** [comment]
Wouldn't build unless `little-state-machine` was a _dependency_ instead of _devDependency_ but then RHF DevTools is still included (and largest asset) in the Production build:
![image](https://user-images.githubusercontent.com/1812179/80167558-4d874f00-85a6-11ea-94cc-d194efb6b674.png)

Any ideas?

**Comment by bluebill1049** [comment]
that's really strang, it should be included by tree shaking... I am confused. what's the bundler you are using CRA, NextJS or Gatsby?

**Comment by cliffordp** [comment]
Parcel v1

**Comment by bluebill1049** [comment]
You may need to upgrade to v2 with tree shake: https://medium.com/@devongovett/parcel-v1-9-0-tree-shaking-2x-faster-watcher-and-more-87f2e1a70f79

**Comment by cliffordp** [comment]
Hmm, can't do that for now. Guess I'll just manually remove it so it doesn't affect the Production build.

I'm unsure why this has to be this way when React Query Devtools works as expected but, thanks again for your efforts.

**Comment by bluebill1049** [comment]
I think we found the root cause: https://github.com/bluebill1049/little-state-machine/issues/36

**Comment by cliffordp** [comment]
Oh, sweet. Let me know if you need me to test something with Parcel v1.

**Comment by bluebill1049** [comment]
hey @cliffordp can you please test this version: react-hook-form-devtools@1.1.4-beta.1

**Comment by cliffordp** [comment]
Just following up here that production build *does* still include DevTools :(

I'm still using Parcel v1 but now on latest versions of RHF (^6.0.4) and DevTools (^2.0.2).

**Comment by bluebill1049** [comment]
I think i got it working for the latest v1, @kotarella1110 is still trying to resolve this for v2.

**Comment by cliffordp** [comment]
v1 of Parcel? not for me but thanks for your efforts

**Comment by bluebill1049** [comment]
try latest v1 :) 
it should work.

**Comment by cliffordp** [comment]
`"parcel-bundler": "^1.12.4",` -- what am I missing?

**Comment by bluebill1049** [comment]
not sure what are you missing but latest v1 i have tested and prod build without dev tool : https://github.com/react-hook-form/devtools/blob/v1.2.1/index.js

https://bundlephobia.com/result?p=react-hook-form-devtools@1.2.0

actually even v2 should not include the devetool as well

https://bundlephobia.com/result?p=react-hook-form-devtools@1.2.0

**Comment by bluebill1049** [comment]
That's really strange...
