### ISSUE TITLE
Love the idea of this, but feels invasive 

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form-devtools#6]
@bluebill1049 I was excited to see the post when you announced the RHF Devtools! However, both myself and my developers felt like it was a bit too invasive and hard to get setup right for a development only tool. 

I think this would fit much nicer as a Browser Extension and i _think_ it is possible. If there is interest, I can take a look at what all would be required to do something like this instead.

**Comment by bluebill1049** [comment]
Yea if you have sometimes please take a look at browser extension. ❤️🎉

**Comment by pzi** [comment]
I wouldn't mind a browser extension, however, if anything, if it could just start in a closed state, that would be handy. Like a `defaultVisibility` prop that accepts an enum of `visible | invisible` or something the like :)

**Comment by bluebill1049** [comment]
@pzi yeah i will install state machine to remember the state as well.

**Comment by bluebill1049** [comment]
here is a PR for persist state @pzi https://github.com/react-hook-form/react-hook-form-devtools/pull/7

**Comment by bluebill1049** [comment]
going to close this issue as i don't have the capacity for this at the moment :)

**Comment by MarkAPhillips** [comment]
> I wouldn't mind a browser extension, however, if anything, if it could just start in a closed state, that would be handy. Like a `defaultVisibility` prop that accepts an enum of `visible | invisible` or something the like :)

Agree with this - my preference would be for it to start in the closed state but having a prop to control this would be useful.
